### ISSUE TITLE
Beacon build failed

### ISSUE THREAD

**Issue by ghost** [tejeez/rtl-trx#1]
> "gcc beacon.c -o beacon -Wall -Wextra -O3 -lrtlsdr
> beacon.c: In function ‘main’:
> beacon.c:63:12: warning: implicit declaration of function ‘rtlsdr_set_dithering’; did you mean ‘rtlsdr_set_bias_tee’? [-Wimplicit-function-declaration]
>   RTL_CHECK(rtlsdr_set_dithering,(dev, 0));
>             ^
> beacon.c:20:9: note: in definition of macro ‘RTL_CHECK’
>   ret = (x y); \
>          ^
> beacon.c:64:12: warning: implicit declaration of function ‘rtlsdr_set_if_freq’; did you mean ‘rtlsdr_set_xtal_freq’? [-Wimplicit-function-declaration]
>   RTL_CHECK(rtlsdr_set_if_freq,(dev, if_freq));
>             ^
> beacon.c:20:9: note: in definition of macro ‘RTL_CHECK’
>   ret = (x y); \
>          ^
> /tmp/cc14BkDP.o: In function `main':
> beacon.c:(.text.startup+0x134): undefined reference to `rtlsdr_set_dithering'
> beacon.c:(.text.startup+0x14d): undefined reference to `rtlsdr_set_if_freq'
> collect2: error: ld returned 1 exit status
> Makefile:7: recipe for target 'beacon' failed"

gcc 7.4.0 ldconfig 2.2.7

**Comment by tejeez** [comment]
Those are functions found in the experimental rtl-sdr branch, https://github.com/keenerd/rtl-sdr
If you install that one, it should build.

You could also try commenting out the calls to rtlsdr_set_dithering and rtlsdr_set_if_freq. To get the correct frequency in this case, you should also change the if_freq value to 3.57e6.

A good option would be adding a check whether these functions are available, but I'm not sure how to do that.

**Comment by ghost** [comment]
@tejeez I builded beacon with experimental branch, but binary dont work `Detached kernel driver
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
./beacon: symbol lookup error: ./beacon: undefined symbol: rtlsdr_set_dithering`

**Comment by tejeez** [comment]
Maybe you still have the original librtlsdr installed and it's trying to use it. You could either try removing the original one, or forcing it to use the experimental library using LD_LIBRARY_PATH. For example, if librtlsdr.so.0 is found under /usr/local/lib, try running:

LD_LIBRARY_PATH=/usr/local/lib ./beacon 1296.1e6 "text"

The world of SDR software is a bit of a mess, so sometimes tricks like this help... Btw, the experimental branch is used since it has optimizations to tune faster. I don't know if the original would even tune fast enough to modulate RTTY.

**Comment by PHPoenX** [comment]
`Detached kernel driver
Found Rafael Micro R820T tuner
Transmitting
[R82XX] PLL not locked!
r82xx_set_freq: failed=-1
Error: rtlsdr_set_center_freq returned -1 at beacon.c:94.` but dump1090 works normally

**Comment by ghost** [comment]
Beacon is working!
Thanks a lot!
